### ISSUE TITLE
Put operator under the Window category of the Keymap

### ISSUE THREAD

**Issue by Intuos5** [martyfouts/change-mode-menu#1]
Continuing the discussion from [Stackexchange](https://blender.stackexchange.com/questions/260279/mode-switch-object-edit-sculpt-as-regular-menu-instead-of-pie-menu/260301?noredirect=1#comment444424_260301)

Hi @martyfouts, 

What I meant with moving the operator to Window is to change the category for the keymap item from 3D view to the Window category. This is where other addons, such as Machin3tools place their mode change pie menu. 
![afbeelding](https://user-images.githubusercontent.com/63149655/163121326-2ce0f188-bea5-472c-8dad-a949f6cadd38.png)
If it resides under Window, it is possible to do mode changes in 2D views as well, although I am not sure whether that is currently a thing in Blender. It's not a big deal, as it mostly helps keeping the keymap organised. Users can move it themselves if need be.

Thanks for your help on this! Much appreciated!

**Comment by martyfouts** [comment]
I've looked into this and it's a trade-off.  The pie menu that I'm replacing actually sets itself up to be in 3D View. After some thought, I think I'll keep it that way.
