### ISSUE TITLE
Add Grease Pencil draw mode

### ISSUE THREAD

**Issue by Intuos5** [martyfouts/change-mode-menu#2]
Hi @martyfouts, 

Could you please add the Grease Pencil mode to the menu when I have a Grease Pencil object selected? Currently, it does not appear in the menu. 
![afbeelding](https://user-images.githubusercontent.com/63149655/169224528-99e7096b-811f-46f1-af56-d9517d53c0aa.png)
![afbeelding](https://user-images.githubusercontent.com/63149655/169224851-c76be97b-ce18-40e5-8dfd-026a0b970e4f.png)

**Comment by martyfouts** [comment]
Definitely a bug, it's supposed to work now.  I'll fix it.

**Comment by Intuos5** [comment]
That would be nice, thank you.

**Comment by martyfouts** [comment]
I had mislabeled draw mode as paint mode in the menu entry.  This change should fix that. Sorry it took me so long to find time to look at it.

**Comment by Intuos5** [comment]
@martyfouts Thanks! No worries, I am happy that you fixed this for me.
